apiVersion: v1
kind: Deployment
metadata: 
  name: casssandra-deployment
  namespace: dev
spec:
  replicas : 1
  selector: 
    matchLabels:
      app: cassandra
  template:
    metadata: 
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:latest
          ports:
            - containerPort: 9042
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "DevCluster"

---
apiVersion : v1
kind: Service
metadata:
  name: cassandra-service
  namespace: dev
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
