apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      initContainers:
      - name: wait-for-cassandra
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z cassandra-service 9042; do echo 'Waiting for Cassandra...'; sleep 5; done;"]
      containers:
      - name: java-backend
        image: task-service-java:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: CASSANDRA_HOST
          value: "cassandra-service"
        - name: REDIS_HOST
          value: "redis-service"
---
apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
  namespace: dev
spec:
  selector:
    app: java-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080