apiVersion : apps/v1
kind : Deployment
metadata : 
  name: postgres-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "task_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
    volumes:
        - name: init-script
          configMap:
            name: postgres-init
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: dev
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS tasks_db;

---

apiVersion: v1
kind: Service
metadata: 
  name: postgres-service
  namespace: dev
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
